export const CLUBS_BY_CATEGORY = {
  "A Cappella": [
    "Amalgamates",
    "Beelzebubs",
    "Enchanted",
    "Full Sound",
    "Jackson Jills",
    "Ladies of Essence",
    "Low-Keys",
    "S-Factor",
    "Shir Appeal",
    "sQ!"
  ],
  "Advocacy": [
    "Access Betters the Lives of Everyone (ABLE)",
    "Action For Sexual Assault Prevention (ASAP)",
    "Active Minds",
    "Advancing Civic Thought In Our Nation (ACTION) (LCS)",
    "African American Foundations and Roots Organization",
    "Allied Scholars for Animal Protection",
    "American Sign Language (ASL) Society",
    "Amnesty International",
    "Artificial Intelligence Society",
    "Asian Student Coalition",
    "Athlete Ally",
    "Blood Cancer United Chapter",
    "Building Relationships through Inclusion and Disability Greater Education: BRIDGE (LCS)",
    "Camp Kesem",
    "Cancer Outreach (LCS)",
    "CARE - Center for Awareness, Resources, and Education",
    "Central American Student Association (CASA)",
    "Chabad",
    "Climate Action",
    "Cooperation and Innovation in Citizenship (CIVIC)",
    "Doctors Without Borders at Tufts",
    "Ears for Peers",
    "Eco Arts Club",
    "Effective Altruism",
    "Engineering Student Council (ESC)",
    "English Department",
    "Environmental Health League",
    "Essential Medical Supplies and Activism for Inequities and Disasters (EMS-AID)",
    "Fluora Initiative",
    "Food Rescue (LCS)",
    "Friends of Black Farmers",
    "Friends of Israel",
    "Green Dot",
    "Hidden Opponent",
    "Hillel",
    "Hooked",
    "Indigenous Center",
    "Indigenous Students' Organization at Tufts",
    "Inglés Para Latinos",
    "International Center",
    "J Street U",
    "Jumbos for Nonprofits",
    "Kids in Nutrition (LCS)",
    "Labor Coalition",
    "Leonard Carmichael Society (LCS)",
    "Mental Health Reps",
    "New England XP (NEXP)",
    "Not Fur Profit",
    "Nuclear Activists (TUNA)",
    "Petey Greene Program",
    "Planned Parenthood Action at Tufts",
    "Project SHARE",
    "Republicans",
    "ResearcHERS",
    "Somos Zine",
    "South Asian Regional Committee",
    "Teach-In CORES",
    "Tisch College of Civic Life",
    "Tufts for Health Equity",
    "Tufts Harm Reduction Education for Alcohol and Drugs",
    "Tufts Student Life Civic Engagement",
    "Tufts University Art Galleries",
    "Tufts University Prison Initiative at Tisch",
    "Tutors for Hope",
    "UNICEF at Tufts",
    "United for Immigrant Justice",
    "Women's Higher Education Now (WHEN)"
  ],
  "Arts / Performance": [
    "ACM SIGGRAPH Student Chapter",
    "Applejam",
    "Art Galleries Student Programming Committee (TUAG SPC)",
    "Artists of Color Union",
    "Ballet Folklorico",
    "Ballroom",
    "Bangin' Everything at Tufts (BEATs)",
    "Bhangra",
    "BlackOut",
    "Burlesque Troupe",
    "Calligraphy Club",
    "Cheap Sox",
    "Children of Cultures of Africa (COCOA)",
    "Club Curate",
    "Corps de Ballet",
    "Crafts Center",
    "Currents Magazine",
    "Department of Music",
    "Digital Fabrication Club",
    "Eco Arts Club",
    "Encendido",
    "Enchanted",
    "English Department",
    "Envision Black Theater",
    "ENVY",
    "Fiber Arts Club",
    "Freshman 15",
    "Full Sound",
    "Graduates In Print",
    "Graphic Novel Club",
    "Harlem Grooves",
    "Hooked",
    "HYPE! Mime Troupe",
    "Institute Sketch Comedy",
    "Jackson Jills",
    "Jumbo Fire & Flow",
    "Jumbo's Revenge",
    "JumboRaas",
    "JumboXR",
    "Korean Dance Association (KoDA)",
    "Ladies of Essence",
    "Local Bard's Players (LBP)",
    "Low-Keys",
    "Melpomene",
    "Mock Trial",
    "Origami Club",
    "Pen, Paint, & Pretzels",
    "Pep Band",
    "Photography Club",
    "Pole Collective",
    "Pulse",
    "Rangeela",
    "Roti and Rum",
    "S-Factor",
    "Salon Soirée",
    "Sarabande Dance Ensemble",
    "Shir Appeal",
    "Skate Sculpture Club",
    "SMFA Clay Club",
    "SMFA Print Club",
    "Spirit of the Creative (SOC)",
    "Stand-Up Comedy Collective",
    "Tamasha",
    "Tap Ensemble",
    "TFL Comedy",
    "The Chuckleducks",
    "Torn Ticket II",
    "Traveling Treasure Trunk (LCS)",
    "Tufts Dance Collective",
    "Tufts Public Harmony",
    "Tufts University Art Galleries",
    "Tufts University Television (TUTV)",
    "Turbo",
    "WIA Tufts",
    "Wind Ensemble",
    "WMFO",
    "WuZee",
    "Zema Dance Troupe"
  ],
  "Club Sports": [
    "Baseball (TUBC) (Club Sport)",
    "Basketball (Men's Club Sport)",
    "Basketball (Women's Club Sport)",
    "Cheerleading (Club Sport)",
    "Climbing Team (Club Sport)",
    "Cricket (Club Sport)",
    "Cycling Team (Club Sport)",
    "Equestrian (Club Sport)",
    "Fencing (Club Sport)",
    "Field Hockey (Club Sport)",
    "Gymnastics (Club Sport)",
    "Ice Hockey (Club Sport)",
    "Lacrosse (Men's Club Sport)",
    "Lacrosse (Women's Club Sport)",
    "Pickleball (Club Sport)",
    "Rugby (Men's Club Sport)",
    "Rugby (Women's Club Sport)",
    "Running Club (Club Sport)",
    "Shotokan Karate (Club Sport)",
    "Ski Team (Club Sport)",
    "Soccer (Men's Club Sport)",
    "Soccer (Women's Club Sport)",
    "Squash (Club Sport)",
    "Swim (Club Sport)",
    "Table Tennis (Club Sport)",
    "Tae Kwon Do (Club Sport)",
    "Tennis (Club Sport)",
    "Ultimate Frisbee (Men's Club Sport)",
    "Ultimate Frisbee - Ewo/Bwo (Women's Club Sport)",
    "Volleyball (Men's Club Sport)",
    "Volleyball (Women's Club Sport)",
    "Water Polo (Men's Club Sport)",
    "Water Polo (Women's Club Sport)"
  ],
  "Community Service": [
    "Action For Sexual Assault Prevention (ASAP)",
    "Advancing Civic Thought In Our Nation (ACTION) (LCS)",
    "American Chemical Society (ACS)",
    "Animal Aid (LCS)",
    "Blood Cancer United Chapter",
    "Brain Exercise Initiative at Tufts",
    "Building Relationships through Inclusion and Disability Greater Education: BRIDGE (LCS)",
    "Camp Kesem",
    "Cancer Outreach (LCS)",
    "Child Development Association (CDA)",
    "China Care",
    "Climate Action",
    "Doctors Without Borders at Tufts",
    "DREAM (LCS)",
    "Ears for Peers",
    "Eliot-Pearson Department of Child Study and Human Development",
    "Eliot-Pearson Master's Student Association",
    "Engineers Without Borders",
    "ESL (LCS)",
    "Essential Medical Supplies and Activism for Inequities and Disasters (EMS-AID)",
    "Food Rescue (LCS)",
    "Girl Scouts (LCS)",
    "Girls in STEM",
    "Giving Camp (LCS)",
    "Hillel",
    "Homelessness Outreach and Meal Equity (HOME)",
    "JumboCode",
    "Jumbos for Nonprofits",
    "Junior Jumbos (LCS)",
    "Kidney Disease Screening and Awareness Program (KDSAP)",
    "Kids in Nutrition (LCS)",
    "Lambda Pi Chi Sorority Inc.",
    "Legacy Project (LCS)",
    "Leonard Carmichael Society (LCS)",
    "Local Bard's Players (LBP)",
    "MEDLIFE",
    "New England XP (NEXP)",
    "Pen Pals",
    "Perfect Potential",
    "PERIOD @ Tufts",
    "Petey Greene Program",
    "Potencia",
    "Project Helping Unhoused Groups",
    "Project Linus (LCS)",
    "Project SHARE",
    "Project Sunshine (LCS)",
    "Red Cross Club",
    "ResearcHERS",
    "Sisters Project Peru at Tufts",
    "Society for Advancement of Chicanos/Hispanics and Native Americans in Science (SACNAS) Chapter",
    "Teach-In CORES",
    "Thirst Project (LCS)",
    "Timmy Global Health",
    "Tisch College of Civic Life",
    "Traveling Treasure Trunk (LCS)",
    "Tufts Bikes",
    "Tufts Emergency Medical Services (TEMS)",
    "Tufts Harm Reduction Education for Alcohol and Drugs",
    "Tufts Public Harmony",
    "Tufts Student Life Civic Engagement",
    "Tutoring",
    "Tutors for Hope"
  ],
  "Culture & Identity": [
    "Access Betters the Lives of Everyone (ABLE)",
    "African American Foundations and Roots Organization",
    "African Student Organization (ASO)",
    "Africana Center",
    "Albanian Student Association",
    "Alternative Jews at Tufts (Alt-J)",
    "American Sign Language (ASL) Society",
    "Arab Student Association",
    "Armenian Student Association",
    "Artists of Color Union",
    "Ascend Global Leaders",
    "Asian American Center",
    "Asian Baptist Fellowship",
    "Asian Student Coalition",
    "Association of Latin American Students (ALAS)",
    "Association of Mixed People at Tufts (AMPT)",
    "Association of South Asians",
    "Athlete Ally",
    "Athletes of Color at Tufts",
    "Ballet Folklorico",
    "Black Graduate Student Union",
    "Black Pre-Health Society",
    "Black Queer Jumbos",
    "Black Student Union",
    "Brazilian Students Association",
    "Cambodian Student Coalition",
    "Caribbean Student Organization",
    "Center for STEM Diversity",
    "Central American Student Association (CASA)",
    "Central Asian Student Union",
    "Chabad",
    "Cheese Club",
    "China Care",
    "Chinese Students and Scholars Association (CSSA)",
    "Chinese Students Association",
    "Community of Faith Exploration and Engagement (COFFEE) Interfaith Student Coalition",
    "Daily Flame",
    "Diabetes Link",
    "Diverse Minds",
    "Division of Student Diversity and Inclusion (DSDI)",
    "Encendido",
    "Ethiopian Eritrean Students Association",
    "FIRST Resource Center",
    "First-Generation Collective (FGC)",
    "French Society",
    "Friends of Black Farmers",
    "Friends of Israel",
    "Full Sound",
    "German Club",
    "Global Education",
    "Graduate Buddhist Mindfulness Sangha",
    "Harlem Grooves",
    "Hawai?i Club",
    "Hellenic Society",
    "Hillel",
    "Hindu Students Association",
    "Hong Kong Student Association",
    "Indigenous Center",
    "Indigenous Students' Organization at Tufts",
    "International Center",
    "International Club",
    "Iranian Students Association (Graduate)",
    "Israeli Culture Club",
    "Italian Club",
    "Italian Tufts Association (ITA)",
    "Japanese Culture Club",
    "JumboRaas",
    "JumBoricuas",
    "Korean International Student Organization",
    "Korean Student Association (KSA)",
    "Ladies of Essence",
    "Lambda Pi Chi Sorority Inc.",
    "Latinx Center",
    "LGBT Center",
    "Mexican Culture Club",
    "Myanmar Student Union (MSU)",
    "ONYX Magazine",
    "Opus Magazine",
    "Pakistani Association for Graduate Students",
    "Pan-Afrikan Alliance",
    "Persian Student Association",
    "Philippine Student Union",
    "Returning Student Organization",
    "Shaping Her Earth (SHE)",
    "Sikh Student Association",
    "Singaporean, Indonesian, and Malaysian Student Association (SIMSA)",
    "Sino-U.S. Relations Group Engagement (SURGE)",
    "Society for Advancement of Chicanos/Hispanics and Native Americans in Science (SACNAS) Chapter",
    "Society of Asian Scientists and Engineers (SASE) Tufts",
    "Society of Latinx Engineers and Scientists",
    "Somos Zine",
    "South Asian Perspectives and Conversation (SAPAC)",
    "South Asian Regional Committee",
    "Student Athlete Advisory Committee",
    "Students of Turkey",
    "Sub-Saharan Africa Research Group (SSARG)",
    "Taiwanese Association of Students at Tufts",
    "Teach-In CORES",
    "TFL Comedy",
    "Thai Students' Association",
    "Torn Ticket II",
    "Tufts University Art Galleries",
    "Vietnamese Students Club",
    "Women In Computer Science (WICS)",
    "Women's Center",
    "WuZee",
    "Zema Dance Troupe"
  ],
  "Fraternity & Sorority Life": [
    "Alpha Phi Alpha Fraternity, Inc.",
    "ATO of Massachusetts",
    "Chi Omega",
    "Delta Tau Delta – Beta Mu Chapter",
    "Delta Upsilon",
    "Epsilon Chapter of Alpha Kappa Alpha Sorority, Incorporated",
    "Inter-Greek Council",
    "Kappa Alpha Theta",
    "Lambda Pi Chi Sorority Inc.",
    "Omega Psi Phi Fraternity, Inc.",
    "Panhellenic Council",
    "Phi Beta Sigma Fraternity Incorporated",
    "Thalia",
    "The Ivy",
    "The Xi Tau Chapter of Delta Sigma Theta Sorority, Inc.",
    "Theta Chi Fraternity",
    "Theta Iota Chapter of Kappa Alpha Psi Fraternity Inc.",
    "Zeta Beta Tau Tufts Omicron Chapter",
    "Zeta Phi Beta Sorority, Inc. – Delta Chi Chapter",
  ],
  "Leonard Carmichael Society (LCS)": [
    "Advancing Civic Thought In Our Nation (ACTION) (LCS)",
    "After School Tutoring and Enrichment (TASTE) (LCS)",
    "Animal Aid (LCS)",
    "Building Relationships through Inclusion and Disability Greater Education: BRIDGE (LCS)",
    "Cancer Outreach (LCS)",
    "College Access Mentoring Initiative (LCS)",
    "DREAM (LCS)",
    "ESL (LCS)",
    "Food Rescue (LCS)",
    "Girl Scouts (LCS)",
    "Girls Inc. (LCS)",
    "Giving Camp (LCS)",
    "Habitat for Humanity (LCS)",
    "Junior Jumbos (LCS)",
    "Kids in Nutrition (LCS)",
    "Legacy Project (LCS)",
    "Leonard Carmichael Society (LCS)",
    "PERIOD @ Tufts",
    "Project Linus (LCS)",
    "Project Sunshine (LCS)",
    "Thirst Project (LCS)",
    "Traveling Treasure Trunk (LCS)",
    "Tutoring",
  ],
  "Political": [
    "Access Betters the Lives of Everyone (ABLE)",
    "Advancing Civic Thought In Our Nation (ACTION) (LCS)",
    "Alexander Hamilton Society",
    "Amnesty International",
    "Climate Action",
    "Cooperation and Innovation in Citizenship (CIVIC)",
    "Democrats",
    "English Department",
    "Environmental Health League",
    "European Horizons",
    "Federalist Society",
    "Friends of Israel",
    "J Street U",
    "JumboVote",
    "Labor Coalition",
    "Pan-Afrikan Alliance",
    "Planned Parenthood Action at Tufts",
    "Republicans",
    "Sino-U.S. Relations Group Engagement (SURGE)",
    "South Asian Perspectives and Conversation (SAPAC)",
    "South Asian Regional Committee",
    "Sub-Saharan Africa Research Group (SSARG)",
    "Tisch College of Civic Life",
    "Tufts Student Life Civic Engagement",
],
  "Pre-Professional & Academic": [
    "180 Degrees Consulting",
    "ACM SIGGRAPH Student Chapter",
    "AI Safety Student Association (TASSA)",
    "Air Force Reserve Officer Training Corps (AFROTC)",
    "Alliance Linking Leaders in Education and Services (ALLIES)",
    "Alpha Kappa Psi",
    "Alt Protein Project",
    "American Chemical Society (ACS)",
    "American Institute of Chemical Engineers (AIChE)",
    "American Sign Language (ASL) Society",
    "American Society for Biochemistry and Molecular Biology",
    "American Society of Civil Engineers",
    "American Society of Mechanical Engineers",
    "Architectural Society",
    "Army ROTC",
    "Artificial Intelligence Society",
    "Ascend Global Leaders",
    "Association of Computing Machinery–Women (Graduate)",
    "Baseball Analytics (BAT)",
    "Biology Union of Graduate Students",
    "Biomedical Engineering and Chemical Engineering Society (BEaChES)",
    "Biomedical Engineering Society",
    "Biotech Club",
    "Biotech Group (TBG)",
    "Black Pre-Health Society",
    "Black Students in Computer Science (BSCS)",
    "Brain Exercise Initiative at Tufts",
    "Career Center",
    "Career Fellows",
    "Center for STEM Diversity",
    "Child Development Association (CDA)",
    "Civil and Environmental Engineering Graduate Student Organization",
    "Computer Science Exchange",
    "Consulting Collective",
    "Debate Society",
    "Economics Society (TES)",
    "Effective Altruism",
    "Electric Racing",
    "Engineering Student Council (ESC)",
    "Engineers Without Borders",
    "English Department",
    "English Society",
    "Financial Group",
    "Geological Society",
    "Global Medical Brigades",
    "GNU/Linux User Group",
    "History Society",
    "Human Factors and Ergonomics Society (THFES)",
    "Institute of Electrical and Electronics Engineers (IEEE)",
    "International Society for Pharmaceutical Engineering",
    "Investment Club",
    "Jumbo Ventures",
    "JumboCode",
    "Lantern Think Tank",
    "Latin American Committee",
    "Leonard Carmichael Society (LCS)",
    "Math Society",
    "Middle East Research Group",
    "Minority Association of Pre-Health Students (MAPS)",
    "Mock Trial",
    "Model United Nations",
    "Mood Psychology",
    "National Society of Black Engineers",
    "National Society of Black Women in Medicine",
    "National Student Data Corps Chapter",
    "NeuroNetwork",
    "Offshore Wind Grad Student Organization",
    "Organization of Graduate Students in Mathematics (OGSM)",
    "Phi Alpha Delta",
    "Pre Medical Society",
    "Pre-Dental Society",
    "Pre-Health Post-Baccalaureate Society",
    "Pre-Law Society",
    "Pre-Optometry Society",
    "Pre-Physician Assistant Society",
    "Pre-Veterinary Society",
    "Product Studio",
    "Project SHARE",
    "Psychology Society",
    "Public Health Society",
    "QuestBridge Scholars (QB)",
    "Real Estate Society",
    "Robotics Club",
    "School of Engineering",
    "Shaping Her Earth (SHE)",
    "Sino-U.S. Relations Group Engagement (SURGE)",
    "Society for Industrial and Applied Mathematics (SIAM) – Graduate",
    "Society of Asian Scientists and Engineers (SASE) Tufts",
    "Society of Latinx Engineers and Scientists",
    "Society of Physics Students",
    "Society of Women Engineers",
    "Solar Vehicle Project",
    "South Asian Regional Committee",
    "Student Occupational Therapy Association (SOTA)",
    "Students for the Exploration and Development of Space (SEDS)",
    "Sub-Saharan Africa Research Group (SSARG)",
    "TAMID at Tufts",
    "Tau Beta Pi – Massachusetts Delta",
    "Tech & Business of Health @ Tufts (TBH)",
    "The ExCollege",
    "The Listening Project",
    "The Women's Network",
    "Tufts Emergency Medical Services (TEMS)",
    "Tufts European Center",
    "Tufts NROTC",
    "Tufts University Television (TUTV)",
    "WIA Tufts",
    "Women Entrepreneurs at Tufts (WE@T)",
    "Women In Computer Science (WICS)",
    "Women in Cybersecurity (WiCyS)",
    "Women in Electrical and Computer Engineering",
    "Women In International Relations",
    "Women in Medicine (WIM)",
    "Women in Product (WiP)",
  ],
  "Publication & Media": [
    "ACM SIGGRAPH Student Chapter",
    "Breakthrough Undergraduate Research Journal",
    "Club Curate",
    "Currents Magazine",
    "English Department",
    "Future Histories Literary Magazine (FH)",
    "Grey Matters",
    "Hemispheres Journal",
    "Her Campus Tufts",
    "Hillel",
    "Historical Review",
    "JumboCast",
    "Lantern Think Tank",
    "Melisma Magazine",
    "Observer",
    "ONYX Magazine",
    "Opus Magazine",
    "Parnassus",
    "Somos Zine",
    "TFL Comedy",
    "Tribune",
    "Tufts Daily",
    "Tufts University Television (TUTV)",
    "Undergraduate Law Review",
    "WMFO",
    "Zamboni Magazine",
  ],
  "Recreation": [
    "Anime Club",
    "Athletics Intramural Program",
    "Badminton Club",
    "Basketball (Men's Club Sport)",
    "Basketball (Women's Club Sport)",
    "Bird Club",
    "Black Queer Jumbos",
    "Book Club",
    "Boxers on the Hill",
    "Camp Kesem",
    "Cheese Club",
    "Chess Club",
    "Climbing Team (Club Sport)",
    "Cricket (Club Sport)",
    "Diverse Minds",
    "Eco Arts Club",
    "Equestrian (Club Sport)",
    "Film Club",
    "Gaming Hub",
    "Girl Gains",
    "Graduate Students Soccer Club",
    "Ice Hockey (Club Sport)",
    "Italian Tufts Association (ITA)",
    "Jumbo Fire & Flow",
    "Jumbo's Revenge",
    "Korean Dance Association (KoDA)",
    "Magic: The Gathering Club",
    "Mechanical Keyboard Club",
    "Quadball",
    "Roundnet Club",
    "Rubik's Cube Club",
    "Rugby (Men's Club Sport)",
    "Rugby (Women's Club Sport)",
    "Running Club (Club Sport)",
    "Shotokan Karate (Club Sport)",
    "Skate Sculpture Club",
    "Ski Team (Club Sport)",
    "SMFA Clay Club",
    "Soccer (Women's Club Sport)",
    "Spirit of the Creative (SOC)",
    "Student Garden",
    "Sudoku Club",
    "Surf Club",
    "Survivor Club",
    "Table Tennis (Club Sport)",
    "Tabletop Gaming",
    "Tennis (Club Sport)",
    "Torn Ticket II",
    "Tufts Bikes",
    "Tufts Mountain Club (TMC)",
    "Ultimate Frisbee (Men's Club Sport)",
    "Volleyball (Men's Club Sport)",
    "Water Polo (Men's Club Sport)",
    "Water Polo (Women's Club Sport)",
  ],
  "Religious & Philosophical": [
    "Asian Baptist Fellowship",
    "Buddhist Mindfulness Sangha (TBMS)",
    "C. Stacey Woods Programming Board",
    "Catholic Community at Tufts",
    "Chabad",
    "Club Curate",
    "Community of Faith Exploration and Engagement (COFFEE) Interfaith Student Coalition",
    "Daily Flame",
    "Graduate Buddhist Mindfulness Sangha",
    "Hillel",
    "Hindu Students Association",
    "Humanist Community at Tufts",
    "Muslim Student Association",
    "Orthodox Christian Fellowship (OCF)",
    "Protestant Students Association (PSA)",
    "Sikh Student Association",
    "University Chaplaincy",
  ],
  "Residential Life": [
    "Office of Residential Life and Learning",
  ],
  "Social / Cultural": [
    "Access Betters the Lives of Everyone (ABLE)",
    "ACM SIGGRAPH Student Chapter",
    "African American Foundations and Roots Organization",
    "Africana Center",
    "AI Safety Student Association (TASSA)",
    "Art Galleries Student Programming Committee (TUAG SPC)",
    "Bird Club",
    "Black Student Union",
    "Center for STEM Diversity",
    "Chabad",
    "Cheese Club",
    "Diverse Minds",
    "Eco Arts Club",
    "Eliot-Pearson Department of Child Study and Human Development",
    "Eliot-Pearson Master's Student Association",
    "Engineering Student Council (ESC)",
    "English Department",
    "First-Generation Collective (FGC)",
    "Girl Gains",
    "Global Education",
    "Graduate Buddhist Mindfulness Sangha",
    "Hillel",
    "Indigenous Center",
    "International Center",
    "International Society for Pharmaceutical Engineering",
    "JumboXR",
    "Korean Dance Association (KoDA)",
    "Latinx Center",
    "LGBT Center",
    "Mood Psychology",
    "Offshore Wind Grad Student Organization",
    "Quadball",
    "Roti and Rum",
    "Shaping Her Earth (SHE)",
    "Sino-U.S. Relations Group Engagement (SURGE)",
    "Society for Advancement of Chicanos/Hispanics and Native Americans in Science (SACNAS) Chapter",
    "Somos Zine",
    "Sub-Saharan Africa Research Group (SSARG)",
    "Survivor Club",
    "TEDxTufts",
    "The Sink Cafe",
    "Tufts Mountain Club (TMC)",
    "Tufts University Art Galleries",
    "Tufts University Social Collective (TUSC)",
    "WIA Tufts",
    "Women In Computer Science (WICS)",
    "Women's Center",
    "Women's Higher Education Now (WHEN)",
],
  "SMFA / Fenway Campus": [
    "ACM SIGGRAPH Student Chapter",
    "Artists of Color Union",
    "Club Curate",
    "Digital Fabrication Club",
    "Fiber Arts Club",
    "Graduates In Print",
    "Graphic Novel Club",
    "JumboXR",
    "Performance Club",
    "Salon Soirée",
    "Skate Sculpture Club",
    "SMFA Clay Club",
    "SMFA Mural Club",
    "SMFA Print Club",
    "SMFA Student Affairs",
    "SMFA Student Government Association (SGA)",
],
  "Social & Programming": [
    "Engineering Student Council (ESC)",
    "Graduate Student Council",
    "SMFA Student Government Association (SGA)",
    "Tufts Community Union (TCU) Elections Commission (ECOM)",
    "Tufts Community Union (TCU) Judiciary (TCUJ)",
    "Tufts Community Union (TCU) Senate",
    "Tufts Community Union (TCU) Treasury",
],
    "University Department": [
      "Academic Advising and Undergraduate Studies",
      "Africana Center",
      "Asian American Center",
      "Career Center",
      "Center for STEM Diversity",
      "Counseling and Mental Health Service",
      "Department of Mathematics",
      "Department of Music",
      "Digital Collections and Archives",
      "Division of Student Diversity and Inclusion (DSDI)",
      "Eliot-Pearson Department of Child Study and Human Development",
      "Eliot-Pearson Master's Student Association",
      "English Department",
      "FIRST Resource Center",
      "Global Education",
      "Graduate School of Arts and Sciences",
      "Health Promotion and Prevention",
      "Health Service",
      "Indigenous Center",
      "International Center",
      "Latinx Center",
      "LGBT Center",
      "Office for Campus Life",
      "Office of Alumni Engagement",
      "Office of Graduate Admissions",
      "Office of the Provost",
      "Public Safety",
      "School of Engineering",
      "StAAR Center",
      "Student Life",
      "The ExCollege",
      "Tisch College of Civic Life",
      "Tufts European Center",
      "Tufts Student Life Civic Engagement",
      "Undergraduate Orientation",
      "University Chaplaincy",
      "Women's Center",
  ],
    "Varsity Athletics": [
      "Tufts Athletics",
      "Athletes of Color at Tufts",
  ],
};